/**
 * levels.js
 *
 * Level definitions for 川渡パズル.
 * Each level is verified solvable by the embedded BFS solver at game load.
 *
 * Constraints flags:
 *   fatherDaughter : father + daughter on same bank without mother → violation
 *   motherSon      : mother + son on same bank without father      → violation
 *   dogMaid        : dog + others on same bank without maid         → violation
 */

"use strict";

const LEVELS = [
  /* ─── STAGE 1–5: チュートリアル ─────────────────── */
  {
    id: 1,
    title: "川を渡ろう",
    subtitle: "チュートリアル①",
    intro: "父と母の二人を右岸に渡そう。",
    characters: ["father", "mother"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 2,
    title: "三人旅",
    subtitle: "チュートリアル②",
    intro: "父・母・息子1の三人を右岸に渡そう。制約はまだなし。",
    characters: ["father", "mother", "son1"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 3,
    title: "四人家族",
    subtitle: "チュートリアル③",
    intro: "四人を渡そう。まだ制約はないけど人数が増えると手数が増える！",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 4,
    title: "娘を守れ",
    subtitle: "制約デビュー",
    intro: "父は母がいないと娘を怒ってしまう。父・母・娘1の三人を渡そう。",
    characters: ["father", "mother", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 5,
    title: "息子を守れ",
    subtitle: "制約デビュー②",
    intro: "母は父がいないと息子を怒ってしまう。父・母・息子1を渡そう。",
    characters: ["father", "mother", "son1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },

  /* ─── STAGE 6–10: 相性制約 ──────────────────────── */
  {
    id: 6,
    title: "両方の制約",
    subtitle: "父娘＋母息子",
    intro: "父娘制約と母息子制約が両方発動！四人を安全に渡そう。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 7,
    title: "息子が二人",
    subtitle: "母息子制約 強化版",
    intro: "息子が二人に。母が息子と同じ場所に父なしではダメ。",
    characters: ["father", "mother", "son1", "son2"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 8,
    title: "娘が二人",
    subtitle: "父娘制約 強化版",
    intro: "娘が二人に。父が娘と同じ場所に母なしではダメ。",
    characters: ["father", "mother", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 9,
    title: "犬がやってきた",
    subtitle: "召使制約",
    intro: "犬は召使がいないと他の人を噛み殺す！召使と犬を上手く使おう。",
    characters: ["father", "mother", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 10,
    title: "ペット同伴旅行",
    subtitle: "全制約デビュー",
    intro: "父娘・母息子・犬の3つ全部の制約が登場！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },

  /* ─── STAGE 11–15: 大家族 ───────────────────────── */
  {
    id: 11,
    title: "息子たちの冒険",
    subtitle: "5人の大家族",
    intro: "息子2人・娘1人の5人家族。母息子制約あり。母が息子と一緒の時は父も必要！",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 12,
    title: "娘たちの冒険",
    subtitle: "5人の大家族",
    intro: "娘2人・息子1人の5人家族。父娘制約あり。父が娘と一緒の時は母も必要！",
    characters: ["father", "mother", "son1", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 13,
    title: "子どもが4人",
    subtitle: "全員制約なし",
    intro: "息子2人・娘2人の6人家族。制約はないが人数が多い！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 14,
    title: "大家族の試練",
    subtitle: "7人＋両制約",
    intro: "召使を加えた7人家族・両制約あり。召使が第3の漕ぎ手になる！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 15,
    title: "フル編成",
    subtitle: "8人全員登場",
    intro: "ついに全員集合！3つの制約すべてあり。これが本来の川渡パズル。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },

  /* ─── STAGE 16–20: 手数制限 ─────────────────────── */
  {
    id: 16,
    title: "手際よく！",
    subtitle: "手数制限 入門",
    intro: "4人・両制約あり。無駄な動きは禁物。制限手数以内にクリアせよ。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 7,
  },
  {
    id: 17,
    title: "時間との勝負",
    subtitle: "手数制限 標準",
    intro: "息子2人に母息子制約。7回以内にクリアせよ。",
    characters: ["father", "mother", "son1", "son2"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 9,
  },
  {
    id: 18,
    title: "最短ルートで",
    subtitle: "手数制限 上級",
    intro: "召使入り7人・両制約・17手以内。ぎりぎりの手数で！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 17,
  },
  {
    id: 19,
    title: "全員・制限あり",
    subtitle: "手数制限 最難関",
    intro: "8人フル編成・全制約・手数制限。最適手順を見つけろ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 24,
  },
  {
    id: 20,
    title: "伝説の渡し守",
    subtitle: "完全制覇",
    intro: "8人・全制約・22手以内。最少手数に近い究極チャレンジ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 22,
  },

  /* ─── STAGE 21–30: 大型の船（3人乗り）────────── */
  {
    id: 21,
    title: "大きな船",
    subtitle: "3人乗り入門",
    intro: "船が大きくなった！3人まで乗れる。まずは制約なしで4人を渡そう。",
    characters: ["father", "mother", "son1", "son2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 22,
    title: "3人船・娘を守れ",
    subtitle: "3人乗り＋父娘制約",
    intro: "3人乗りでも父娘制約は有効！息子と娘を含む4人を渡そう。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 23,
    title: "3人船・家族5人",
    subtitle: "3人乗り＋母息子制約",
    intro: "5人家族を3人船で渡そう。母息子制約に注意。",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 24,
    title: "3人船・両制約",
    subtitle: "3人乗り＋父娘＋母息子",
    intro: "5人・両方の制約あり。3人船でもルールは変わらない。",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 25,
    title: "3人船・6人家族",
    subtitle: "3人乗り・子ども4人",
    intro: "子ども4人の6人家族を3人船で渡そう。制約はなし。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 26,
    title: "3人船・6人＋全制約",
    subtitle: "3人乗り・難関",
    intro: "6人家族に両方の制約。3人まとめて渡せるが、帰りが問題。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 27,
    title: "3人船と犬",
    subtitle: "3人乗り＋召使制約",
    intro: "6人編成。犬の制約と3人船の組み合わせ。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 28,
    title: "3人船・全員集合",
    subtitle: "3人乗り・フル編成",
    intro: "8人全員を3人船で！全制約あり。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 29,
    title: "3人船・時間勝負",
    subtitle: "3人乗り・手数制限",
    intro: "8人全員・全制約・手数制限あり。3人船を活かせ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 13,
  },
  {
    id: 30,
    title: "3人船・最適解",
    subtitle: "3人乗り・難関チャレンジ",
    intro: "3人船・8人・全制約。最少手数に挑め！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 11,
  },

  /* ─── STAGE 31–40: 変則配置 ─────────────────── */
  {
    id: 31,
    title: "息子と娘の混合",
    subtitle: "5人・父娘制約",
    intro: "息子1人・娘2人の5人家族。父娘制約あり。娘を守れ！",
    characters: ["father", "mother", "son1", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 32,
    title: "息子2人と娘1人",
    subtitle: "5人・母息子制約",
    intro: "息子2人・娘1人の5人家族。母息子制約あり。息子を守れ！",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 33,
    title: "息子たちと犬",
    subtitle: "6人・母息子＋召使制約",
    intro: "息子2人と犬がいる6人。母息子制約と召使制約が絡む。",
    characters: ["father", "mother", "son1", "son2", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 34,
    title: "娘たちと犬",
    subtitle: "6人・父娘＋召使制約",
    intro: "娘2人と犬がいる6人。父娘制約と召使制約が絡む。",
    characters: ["father", "mother", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 35,
    title: "6人＋手数制限",
    subtitle: "制約あり・タイトな制限",
    intro: "6人家族・母息子制約に手数制限！13手以内に計画的に動かそう。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 13,
  },
  {
    id: 36,
    title: "7人家族の試練",
    subtitle: "全制約・7人",
    intro: "息子1人・娘1人に犬と召使。全制約・7人編成。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 37,
    title: "息子2人と全制約",
    subtitle: "7人・全制約",
    intro: "息子2人に召使と犬。7人編成・全制約。",
    characters: ["father", "mother", "son1", "son2", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 38,
    title: "娘2人と全制約",
    subtitle: "7人・全制約",
    intro: "娘2人に召使と犬。7人編成・全制約。",
    characters: ["father", "mother", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 39,
    title: "8人・21手以内",
    subtitle: "フル編成・手数制限",
    intro: "8人全員・全制約・21手以内！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 21,
  },
  {
    id: 40,
    title: "8人・20手以内",
    subtitle: "フル編成・最難関",
    intro: "20手でクリアできるか？最適手順を探せ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 20,
  },

  /* ─── STAGE 41–50: 制約マスター ─────────────── */
  {
    id: 41,
    title: "召使デビュー・3人",
    subtitle: "犬と召使の基礎",
    intro: "父・召使・犬の3人。犬の扱いに慣れよう。",
    characters: ["father", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 42,
    title: "召使と家族",
    subtitle: "4人・召使制約",
    intro: "父母と召使・犬の4人。召使がカギ。",
    characters: ["father", "mother", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 43,
    title: "息子と犬の旅",
    subtitle: "5人・母息子＋召使制約",
    intro: "息子と犬の両方を抱えた5人旅。",
    characters: ["father", "mother", "son1", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 44,
    title: "娘と犬の旅",
    subtitle: "5人・父娘＋召使制約",
    intro: "娘と犬の両方を抱えた5人旅。",
    characters: ["father", "mother", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 45,
    title: "息子・娘・犬",
    subtitle: "6人・全制約",
    intro: "息子1人・娘1人・犬・召使の6人。全制約の基本形。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 46,
    title: "6人・全制約・制限",
    subtitle: "6人・全制約・手数制限",
    intro: "6人・全制約に手数制限が加わった！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 13,
  },
  {
    id: 47,
    title: "息子2人・犬あり",
    subtitle: "7人・全制約",
    intro: "息子2人に犬と召使。7人・全制約。",
    characters: ["father", "mother", "son1", "son2", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 48,
    title: "娘2人・犬あり",
    subtitle: "7人・全制約",
    intro: "娘2人に犬と召使。7人・全制約。",
    characters: ["father", "mother", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 49,
    title: "7人・手数制限",
    subtitle: "全制約・手数制限",
    intro: "7人・全制約に手数制限。集中しよう！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 15,
  },
  {
    id: 50,
    title: "折り返し地点",
    subtitle: "50ステージ記念",
    intro: "50ステージ目！8人フル編成・全制約・19手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 19,
  },

  /* ─── STAGE 51–60: 3人船エキスパート ────────── */
  {
    id: 51,
    title: "3人船・息子2人",
    subtitle: "大型船・母息子制約",
    intro: "3人乗り・息子2人の4人家族。母息子制約あり。",
    characters: ["father", "mother", "son1", "son2"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 52,
    title: "3人船・娘2人",
    subtitle: "大型船・父娘制約",
    intro: "3人乗り・娘2人の4人家族。父娘制約あり。",
    characters: ["father", "mother", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 53,
    title: "3人船・犬の同行",
    subtitle: "大型船・召使制約",
    intro: "父母・召使・犬を3人船で。召使制約に注意。",
    characters: ["father", "mother", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 54,
    title: "3人船・5人全制約",
    subtitle: "大型船・制約フル",
    intro: "5人家族・両制約・3人船。",
    characters: ["father", "mother", "son1", "daughter1", "maid"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 55,
    title: "3人船・6人全制約",
    subtitle: "大型船・難関",
    intro: "6人・全制約・3人船。効率よく渡ろう。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 56,
    title: "3人船・6人制限あり",
    subtitle: "大型船・手数制限",
    intro: "6人・全制約・3人船に手数制限！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 9,
  },
  {
    id: 57,
    title: "3人船・7人",
    subtitle: "大型船・7人全制約",
    intro: "息子2人・娘1人・召使・犬の7人・3人船。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 58,
    title: "3人船・7人制限",
    subtitle: "大型船・7人・手数制限",
    intro: "7人・全制約・3人船・手数制限付き！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 11,
  },
  {
    id: 59,
    title: "3人船・8人制限",
    subtitle: "大型船・フル編成・制限",
    intro: "8人・全制約・3人船・手数制限！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 13,
  },
  {
    id: 60,
    title: "3人船・最適解",
    subtitle: "大型船・究極チャレンジ",
    intro: "3人船・8人・全制約。最少手数に挑め！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 11,
  },

  /* ─── STAGE 61–70: スピードチャレンジ ───────── */
  {
    id: 61,
    title: "3手でクリア",
    subtitle: "最速チャレンジ",
    intro: "父母と息子の3人。3手以内でクリアせよ！",
    characters: ["father", "mother", "son1"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 3,
  },
  {
    id: 62,
    title: "5手でクリア",
    subtitle: "4人・スピード",
    intro: "4人を5手でクリアせよ！無駄な動きは禁物。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 5,
  },
  {
    id: 63,
    title: "7手でクリア",
    subtitle: "5人・スピード",
    intro: "5人・制約なし・7手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 7,
  },
  {
    id: 64,
    title: "制約あり・7手",
    subtitle: "4人・制約・スピード",
    intro: "両制約あり・4人・7手でクリア。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 7,
  },
  {
    id: 65,
    title: "9手チャレンジ",
    subtitle: "5人・母息子制約・スピード",
    intro: "5人・母息子制約・9手以内。最適な手順を見つけろ！",
    characters: ["father", "mother", "son1", "son2", "daughter1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 9,
  },
  {
    id: 66,
    title: "召使スピード",
    subtitle: "5人・召使制約・スピード",
    intro: "召使と犬を含む5人・9手以内。",
    characters: ["father", "mother", "maid", "dog", "son1"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 9,
  },
  {
    id: 67,
    title: "11手チャレンジ",
    subtitle: "6人・母息子制約・スピード",
    intro: "6人・母息子制約・11手以内。素早く渡ろう！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 11,
  },
  {
    id: 68,
    title: "13手チャレンジ",
    subtitle: "7人・全制約・スピード",
    intro: "7人・全制約・13手以内！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 13,
  },
  {
    id: 69,
    title: "17手チャレンジ",
    subtitle: "8人・全制約・最少手数",
    intro: "8人・全制約・17手以内！これは最少手数に近い究極の挑戦。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 17,
  },
  {
    id: 70,
    title: "自由な挑戦",
    subtitle: "8人・全制約・記録更新",
    intro: "8人フル編成・全制約。制限なし！何手でクリアできる？",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },

  /* ─── STAGE 71–80: 特殊編成 ─────────────────── */
  {
    id: 71,
    title: "父ひとりが漕ぐ",
    subtitle: "父だけが舵を取る",
    intro: "母がいない。父だけが舟をこげる5人の旅。",
    characters: ["father", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 72,
    title: "母ひとりが漕ぐ",
    subtitle: "母だけが舵を取る",
    intro: "父がいない。母だけが舟をこげる5人の旅。",
    characters: ["mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 73,
    title: "召使だけが漕ぐ",
    subtitle: "召使だけが舵を取る",
    intro: "父も母もいない！召使だけが舟をこげる4人旅。犬の扱いに注意。",
    characters: ["son1", "son2", "maid", "dog"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 74,
    title: "3人船・父だけ漕ぐ",
    subtitle: "大型船・父だけが舵を取る",
    intro: "3人乗り・父だけが舟をこげる5人の旅。一気に渡ろう！",
    characters: ["father", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 75,
    title: "3人船・母だけ漕ぐ",
    subtitle: "大型船・母だけが舵を取る",
    intro: "3人乗り・母だけが舟をこげる5人の旅。",
    characters: ["mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: false, motherSon: false, dogMaid: false },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 76,
    title: "3人船・スピード①",
    subtitle: "大型船・タイムアタック",
    intro: "3人乗り・4人・両制約・5手以内。",
    characters: ["father", "mother", "son1", "daughter1"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: 5,
  },
  {
    id: 77,
    title: "3人船・スピード②",
    subtitle: "大型船・6人・タイムアタック",
    intro: "3人乗り・6人・両制約・7手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 3,
    moveLimit: 7,
  },
  {
    id: 78,
    title: "3人船・犬スピード",
    subtitle: "大型船・全制約・タイムアタック",
    intro: "3人乗り・6人・全制約・7手以内。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 7,
  },
  {
    id: 79,
    title: "制約三重奏",
    subtitle: "7人・全制約・手数制限",
    intro: "7人・全制約・15手以内。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 15,
  },
  {
    id: 80,
    title: "制約三重奏・限界",
    subtitle: "7人・全制約・タイト",
    intro: "7人・全制約・13手以内。最適手順を見つけろ！",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 13,
  },

  /* ─── STAGE 81–90: エキスパート ─────────────── */
  {
    id: 81,
    title: "エキスパート①",
    subtitle: "8人・2人船・制限18",
    intro: "8人フル・全制約・18手以内！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 18,
  },
  {
    id: 82,
    title: "エキスパート②",
    subtitle: "3人船・8人・制限11",
    intro: "3人乗り・8人フル・全制約・11手以内！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 11,
  },
  {
    id: 83,
    title: "エキスパート③",
    subtitle: "2人船・6人・制限11",
    intro: "6人・全制約・11手以内。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 11,
  },
  {
    id: 84,
    title: "エキスパート④",
    subtitle: "2人船・7人・制限13",
    intro: "7人・全制約・13手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 13,
  },
  {
    id: 85,
    title: "エキスパート⑤",
    subtitle: "3人船・7人・制限11",
    intro: "3人乗り・7人・全制約・11手以内！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 11,
  },
  {
    id: 86,
    title: "エキスパート⑥",
    subtitle: "2人船・5人・制限7",
    intro: "5人・両制約・7手以内。",
    characters: ["father", "mother", "son1", "daughter1", "maid"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 7,
  },
  {
    id: 87,
    title: "エキスパート⑦",
    subtitle: "召使なし・犬あり",
    intro: "召使なしで犬がいる7人！犬の制約は発動しないが、父娘制約は健在。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "dog"],
    constraints: { fatherDaughter: true, motherSon: false, dogMaid: false },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 88,
    title: "エキスパート⑧",
    subtitle: "6人・全制約・制限11再挑戦",
    intro: "6人・全制約・11手以内。エキスパート③より難しい編成。",
    characters: ["father", "mother", "son2", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 11,
  },
  {
    id: 89,
    title: "エキスパート⑨",
    subtitle: "3人船・8人・制限9",
    intro: "3人乗り・8人フル・全制約・9手以内！究極に近い。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 9,
  },
  {
    id: 90,
    title: "エキスパート⑩",
    subtitle: "2人船・8人・最少手数",
    intro: "8人フル・全制約・17手以内。これが2人船の最少手数だ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 17,
  },

  /* ─── STAGE 91–100: 伝説 ─────────────────────── */
  {
    id: 91,
    title: "伝説①",
    subtitle: "試練の序章",
    intro: "8人・全制約・3人船・9手。これが「伝説」への入口。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 9,
  },
  {
    id: 92,
    title: "伝説②",
    subtitle: "2人船・限界への挑戦",
    intro: "8人・全制約・2人船・17手。最少手数でのクリアを目指せ。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 17,
  },
  {
    id: 93,
    title: "伝説③",
    subtitle: "3人船・7人・最速",
    intro: "3人船・7人・全制約・9手。至難の業。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 9,
  },
  {
    id: 94,
    title: "伝説④",
    subtitle: "ミックス難題",
    intro: "7人・両制約・2人船・11手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: false },
    boatCapacity: 2,
    moveLimit: 11,
  },
  {
    id: 95,
    title: "伝説⑤",
    subtitle: "3人船・7人・7手",
    intro: "3人船・7人・全制約・7手以内。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: 7,
  },
  {
    id: 96,
    title: "伝説⑥",
    subtitle: "2人船・6人・9手",
    intro: "6人・全制約・2人船・9手以内。",
    characters: ["father", "mother", "son1", "daughter1", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 9,
  },
  {
    id: 97,
    title: "伝説⑦",
    subtitle: "究極の8人2人船",
    intro: "8人フル・全制約・2人船・17手以内。最少手数に挑め。",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 17,
  },
  {
    id: 98,
    title: "伝説⑧",
    subtitle: "3人船・完全最適解",
    intro: "8人フル・全制約・3人船・制限なし。最少手数を記録せよ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 3,
    moveLimit: null,
  },
  {
    id: 99,
    title: "伝説⑨",
    subtitle: "最後の試練",
    intro: "8人・全制約・2人船・制限なし。最少手数を更新せよ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: null,
  },
  {
    id: 100,
    title: "川渡の神様",
    subtitle: "完全制覇・全クリア",
    intro: "ついに100ステージ目。8人・全制約・2人船・17手以内。これが真の最少手数だ！",
    characters: ["father", "mother", "son1", "son2", "daughter1", "daughter2", "maid", "dog"],
    constraints: { fatherDaughter: true, motherSon: true, dogMaid: true },
    boatCapacity: 2,
    moveLimit: 17,
  },
];
